---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-test-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-test-ci
  template:
    metadata:
      labels:
        app: redis-test-ci
    spec:
      containers:      
      - name: redis-test-ci
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-test-ci
  namespace: default
spec:
  selector:
    app: redis-test-ci
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ci
  template:
    metadata:
      labels:
        app: test-ci
    spec:
      containers:      
      - name: test-ci
        image: praxamos/test-ci:2502f6533b8fe932399770b60bb4afd5f1cae06b
        env:
        - name: REDIS_URL
          value: redis-test-ci:6379
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redis-test-ci
  namespace: default
spec:
  selector:
    app: redis-test-ci
  ports:
  - name: redis
    protocol: TCP
    port: 8080
    targetPort: 8080    